apiVersion: v1
kind: Service
metadata:
  name: hello-gitops
  labels:
    app: hello-gitops
spec:
  type: NodePort
  ports:
    - name: http
      port: 8050
      targetPort: http

  # Note here that we match both the app and the version
  selector:
    app: hello-gitops
    version: v1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops-v1
  labels:
    app: hello-gitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-gitops
      version: v1.0.0
  template:
    metadata:
      labels:
        app: hello-gitops
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: hello-gitops
        image: containersol/k8s-deployment-strategies
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5