apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-v1.yaml
- app-v2.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: osem/hello-gitops
  newTag: 4e396c5a0bfefdf4b9eec601cf3426ffb14fb39e
